 [theme]
base = "light"
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true